version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 99
  reviewers:
  - varunsridharan
  assignees:
  - varunsridharan
